### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by Ecalpal** [ltkong218/FastFlowNet#16]
Hi, @ltkong218,

Thanks for your exciting work, do you have any plan to release the evaluation code of MPI-Sitel training and KITTI?

**Comment by ltkong218** [comment]
I will release the train and evaluation code of FastFlowNet with a future paper. For emergency, you can refer to PWC-Net (CVPR 2018, Caffe), RAFT (ECCV 2020, PyTorch), UFlow (ECCV 2020, Tensorflow) and so on.
