### ISSUE TITLE
TensorRT docker image with FastFlowNet

### ISSUE THREAD

**Issue by pullmyleg** [ltkong218/FastFlowNet#23]
Thanks for the repo! 

In case other people are struggling to get a TensorRT environment working: [https://hub.docker.com/r/pullmyleg/tensorrt8_cuda11.3_pytorch1.10.2_fastflownet ](https://hub.docker.com/r/pullmyleg/tensorrt8_cuda11.3_pytorch1.10.2_fastflownet )

**Comment by ltkong218** [comment]
Thanks for your contribution!

I have added your Docker TensorRT environment for FastFlowNet to the [README.md](https://github.com/ltkong218/FastFlowNet#readme) file of this repository. Thanks!

**Comment by pullmyleg** [comment]
@zhanghanduo from memory I started with the base nvidia GPU docker container. Password for sudo will be: nvidia
