### ISSUE TITLE
使用pre-trained(things3d)模型，在MpiSintelClean_Training数据集上epe只有4.3，达不到论文中的水平

### ISSUE THREAD

**Issue by worhar** [ltkong218/FastFlowNet#24]
你好，我在复现您的算法时，发现精度只能达到题述水平，我确认以下几点和您的实现一致：

**Comment by worhar** [comment]
1、数据归一化
2、网络结构与权重
3、预测结果使用bilinear缩放，乘以20.0

**Comment by ltkong218** [comment]
The EPE on MPI Sintel Clean of FastFlowNet pre-trained on FlyingThings3D is 2.89 in the paper, while you get the result of 4.3. I think the big difference may be the misconfigured PyTorch or correlation layer.

I suggest you change the running environment, such as PyTorch version and correlation version, to try it again.

Or you can train the model with the data augmentation code in MaskFlowNet to reproduce it.

**Comment by worhar** [comment]
是的，你的猜测是对的。是因为Pytorch版本的问题，高于1.3的版本grid_sample()中align_corners参数默认值发生了变化，导致了这一巨大的误差。
