### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by Wenjie64** [ltkong218/FastFlowNet#9]
Hello, I use the model to train my dataset, but the tensor size after pooling and up sampling is different, so the torch.cat command cannot be executed(such as cat6 = torch.cat([cv6, r16, flow7_up], 1)). I used the following function to process the data, and then this error occurred. Do you know how to solve this problem? Or how to deal with the problem of inconsistent tensor size?

![image](https://user-images.githubusercontent.com/19542713/130974127-406a5b1e-4569-4d74-a014-8d1d6275e511.png)

**Comment by ltkong218** [comment]
During training, you should make sure that the height and width of cropped patches are divisible by 64.

**Comment by Wenjie64** [comment]
Thanks, the problem has been resolved, I add the .clone() in this code
vgrid[:, 0, :, :] = 2.0 * vgrid[:, 0, :, :] / max(W-1, 1) - 1.0
